import  Container  from '../Conponents/Container'
import SectionTitle from '../Conponents/SectionTitle'

const About = () => {
  return (
    <Container>
      <SectionTitle title="About page" />
      <p className="text-base mt-2 tracking-wide text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores perspiciatis iusto amet eius, tempore officia ipsum fugit itaque similique nisi, blanditiis eligendi ad necessitatibus ullam repellat omnis ab in dolorum ea totam quos, eum nostrum? Nisi deserunt voluptas provident facilis ipsa vitae hic laudantium eligendi tempore obcaecati totam, eius aperiam dolor repellat. Dolore esse aut porro iste ab. Ipsa explicabo sapiente quas tempore libero, et exercitationem vero enim suscipit nihil at temporibus eum autem nisi odio incidunt iusto porro odit. Veniam reprehenderit unde enim iure vel non! Nihil explicabo, mollitia vel enim eius voluptatem nam laudantium consectetur culpa quae odit nesciunt totam harum sint ipsa. Earum vero totam labore. Delectus deserunt ratione sequi vitae modi. Temporibus, rerum? Ex, laudantium. Ullam voluptas exercitationem dolores dolore quod maxime ea provident corrupti quas deserunt magni animi voluptate quasi esse, fugit odit molestias officia vitae. Aliquid cumque voluptate, rerum amet impedit nesciunt quibusdam ab? Temporibus incidunt nobis voluptas sunt modi quam similique omnis eius a sapiente placeat culpa enim fugiat vel ducimus quo id voluptates
         nihil explicabo, vitae alias dicta sit nisi. Ab eum magnam unde dicta fugiat temporibus architecto voluptates illum porro possimus? Officia cum repellendus dicta? Explicabo ullam, quae, voluptatum voluptate sit quasi ipsa nulla consequatur quod pariatur blanditiis odio fugiat dolore tempora incidunt perspiciatis optio repellat officiis illum natus quia sint sunt laboriosam! Architecto sapiente itaque eos corporis autem exercitationem, delectus ipsum neque quod cum totam, odit facere ea dolore provident earum consequuntur. Consectetur amet saepe eum ducimus praesentium minus dignissimos doloribus nulla, provident soluta sapiente excepturi autem optio nobis hic eos possimus? Possimus sit temporibus minus autem ipsum doloribus quam, tenetur quisquam numquam libero. Eos voluptatibus cum repellat odio laudantium provident autem sint iusto magnam maiores quasi, quisquam repellendus amet hic. Repellendus, voluptatem officiis et laboriosam qui dolores omnis ab quam quaerat quo reiciendis sed, rem, vero rerum nesciunt! Nostrum labore tenetur fuga natus ratione veritatis asperiores odio repellat enim!</p>
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum eligendi aut nihil iste a, hic culpa magnam id quod sequi natus ut, ipsa consectetur. Id in aut ratione minus molestiae debitis nulla voluptates, minima rerum animi assumenda repellat blanditiis ducimus ea? Totam odit placeat voluptates odio ea a nostrum adipisci quisquam dolor ipsa accusantium, porro nulla officiis veniam velit aperiam perferendis nemo quam eligendi tenetur ratione quo provident iste. Quaerat quasi quos itaque, placeat quia tempora magnam debitis? Doloribus in cumque suscipit ad reiciendis minus impedit et, sapiente ullam mollitia illum odio quaerat soluta, temporibus, autem nesciunt explicabo. Tempore, soluta doloremque. Expedita corporis ipsam quia sint mollitia cumque excepturi. Placeat harum et in tempora error vitae aspernatur, dolor obcaecati voluptas veniam deserunt quam! Eligendi harum quaerat labore dolorum necessitatibus a libero beatae? Nemo illum, rerum earum ab corrupti amet error explicabo porro corporis aperiam id dicta nam dignissimos voluptas unde molestiae ullam nihil deserunt cumque? Soluta sequi minus nihil at explicabo. Explicabo, obcaecati veritatis labore voluptates dolore debitis deserunt, impedit itaque quis nesciunt id, minus blanditiis 
  consequuntur ducimus natus eius veniam rerum aperiam. Voluptatum omnis debitis nisi eos doloribus unde illum? Minima doloribus eaque dolore, deleniti ratione, quidem corporis accusantium necessitatibus sunt explicabo doloremque veritatis debitis, iusto molestias! Voluptatem necessitatibus iure ipsum nesciunt debitis adipisci saepe aspernatur sed totam aliquam? Magnam tenetur deleniti facilis a quod cupiditate illo sunt, quos asperiores, autem ea quisquam eveniet inventore soluta, distinctio fugit ipsam nisi corrupti est in molestias rem! Neque obcaecati, doloribus repellendus repudiandae possimus fuga modi maiores? Unde dicta provident necessitatibus autem obcaecati ea quo eum dolor consequuntur velit veritatis enim, nostrum cum excepturi rem, dolorum mollitia delectus illo fuga voluptate et quas quae. Eos ullam, autem quod obcaecati numquam omnis. Vitae odit minima vel sed atque eaque reprehenderit voluptatibus dicta. Commodi deleniti nemo sunt, veritatis rem totam quasi, quia eos ex id ut repudiandae fugiat voluptate quidem illo reprehenderit assumenda eligendi culpa saepe alias praesentium iste natus asperiores? 
  Pariatur dolores, autem iste, cumque dolore maiores temporibus fugiat, ut ab iusto ratione? Quibusdam, repudiandae vel. Amet possimus quisquam quis quam? Ratione, sunt porro veritatis excepturi commodi, est officiis voluptate facilis omnis delectus, doloremque numquam. Neque excepturi molestiae consequatur nisi? Aliquam temporibus facere ab quod, alias architecto rem quo vel. Inventore maiores voluptate animi harum. Accusamus non dolor vel, nihil velit corporis dolore voluptatibus adipisci, illo libero labore assumenda accusantium impedit porro. Expedita.</p>
    </Container>
  )
}

export default About